### ISSUE TITLE
Select Font dialog shows all text in Italic?

### ISSUE THREAD

**Issue by Anton-V-K** [sskodje/WpfColorFont#1]
All texts (except for Sample Text) in Select Font dialog are shown italicized...

![wpfcolorfontdialog-select_font-italic](https://user-images.githubusercontent.com/20116984/27488346-3eaa5904-5850-11e7-90e3-75cb0a473924.png)

Is it a glitch or done intentionally?
Windows 7 64-bit SP1 (Visual Studio Community 2017)

**Comment by sskodje** [comment]
You are correct in that it is a glitch. The text inherited the style of the group headers. Whoops :)

I'll fix it right away.

**Comment by Anton-V-K** [comment]
Thanks for the fix! I've downloaded the version 1.0.3 and the issue seems to be fixed.
