### ISSUE TITLE
Cannot select/handle "non-standard" font size

### ISSUE THREAD

**Issue by Anton-V-K** [sskodje/WpfColorFont#2]
1. The dialog allows to select a font size from a list box, which limits possibility to use an arbitrary size.
2. And when an unexpected font size is fed into the dialog, it displays it incorrectly (f.i., 55 will be shown as 10, and if OK is pressed 10 is passed further).

Though p.1 is rather hard to fix without redesigning the dialog, I propose to handle this problem at least partially and fix p.2: when an unexpected font size is encountered, the dialog shouldn't touch it unless the user explicitly selects a new size.

**Comment by sskodje** [comment]
Hello, and thanks for the feedback! I have modified the dialog so you optionally can input arbitrary font sizes, as well as input your own custom font size range if you want to use a still limited (but different) allowed size range. It should be on Nuget as of now.

**Comment by dabnoj** [comment]
hello, can we hide some content? like hide color selector?

**Comment by sskodje** [comment]
It was a pretty quick feature to implement, so i made the changes for you. Just input the bool in constructor whether to show or hide color selector from the lastest version.

Also don't forget if you want to customize or change more stuff around for you own needs, you can always just fork!
