### ISSUE TITLE
What about localization?

### ISSUE THREAD

**Issue by Anton-V-K** [sskodje/WpfColorFont#4]
Is it possible to prepare the component (as NuGet packaged) which would support other languages?
There are only few text strings to translate, and I can help with translating English to Russian and Ukrainian...

**Comment by sskodje** [comment]
It's possible, but i don't have any experience with localization, so i can't help you. If you decide to fork and figure it out, you can of course make a pull request and i'll update the nuget!

**Comment by HMBSbige** [comment]
Could you update the nuget?

**Comment by sskodje** [comment]
done
